### ISSUE TITLE
new zoom level problem

### ISSUE THREAD

**Issue by sgdoerfler** [rectangle-dbmi/Realtime-Port-Authority#223] opened 2015-10-04 05:21 UTC
Sometimes when returning to the app, it forgets the previous zoom level and zooms all the way out so all selected routes are shown in full. This appears to be a regression in the last 2 weeks or so. It's happened half a dozen times, but I haven't pinned down the steps to reproduce it at will.

**Comment by epicstar** [comment] 2015-10-04 17:36
Interesting... I will try my best to reproduce this.

**Comment by epicstar** [comment] 2015-10-30 03:10
K I found out what it is... The Google Maps API in Google Play Services 8.1 randomly memory leaks from various objects and the Camera Location is one of them..... The solution is to wait for 8.3 of Google Play Services.

**Comment by epicstar** [comment] 2015-10-30 04:44
... see #225 because this is the only case where my camera will reset. It sucks I know but I can't seem to stop this leak even if I do unset the camera in onDestroy()

**Comment by epicstar** [comment] 2015-12-06 01:24
I'm going to do a take 2 on the app since we are going to attempt to make this actually material... see #261 since everything is bad from the start...

**Comment by epicstar** [comment] 2016-05-15 03:14
Not seeing any camera problems with the beta versions now. There are other bugs I'm trying to fix with the new features I put in, but that should be done soon.

**Comment by epicstar** [comment] 2016-06-04 18:12
This is fixed with 7.0.0. LMK if there are still problems, @sgdoerfler

**Closed by epicstar** 2016-06-04 18:12 UTC
Labels: bug
