### ISSUE TITLE
Needs a better app icon 

### ISSUE THREAD

**Issue by toddmedema** [rectangle-dbmi/Realtime-Port-Authority#314] opened 2016-12-18 17:23 UTC
Perhaps a bus? Right now it looks like nothing, is unnecessarily difficult to visually find amongst other apps

**Comment by TheAndroidMaster** [comment] 2016-12-18 18:22
This is a duplicate of #204. We've been working on a new one for a while, but haven't come up with anything that good yet.

**Comment by epicstar** [comment] 2016-12-28 22:11
As @TheAndroidMaster said, this is a duplicate of #204. Closing this now.

**Closed by epicstar** 2016-12-28 22:11 UTC
Labels: duplicate
