### ISSUE TITLE
28X data missing

### ISSUE THREAD

**Issue by altayhunter** [rectangle-dbmi/Realtime-Port-Authority#330] opened 2019-12-18 16:28 UTC
PAT Track has not been able to show data for the 28X (or even draw the route on the map) recently. TrueTime is still able to show realtime data for this route [in the web interface](http://truetime.portauthority.org/bustime/wireless/html/eta.jsp?route=Port+Authority+Bus%3A28x&direction=Port+Authority+Bus%3AINBOUND&id=Port+Authority+Bus%3A20015&showAllBusses=on), so it doesn't seem to be a problem with Port Authority's servers.

**Comment by epicstar** [comment] 2019-12-18 17:14
Acknowledged. TrueTime changed 28X to 28x so that might be the cause (or
maybe bc I'm stuck on v2).... I will be working on the app during the break.

From,
Jeremy

**Comment by mikeantonacci** [comment] 2020-05-16 23:08
This seems to be resolved. I can see the 28X in released app and in my local build from the develop branch.

**Comment by mikeantonacci** [comment] 2020-05-18 03:06
Closing as no longer occurring. I used to have the missing 28X but it seems to be working now. Probably Port Authority fixed it on their end.

**Closed by mikeantonacci** 2020-05-18 03:06 UTC
