### ISSUE TITLE
Route for bus 29 is drawn incorrectly

### ISSUE THREAD

**Issue by altayhunter** [rectangle-dbmi/Realtime-Port-Authority#350] opened 2023-03-23 17:36 UTC
The route for bus 29 is drawn incorrectly in the app as the result of the Penn Station stop being incorrectly placed up on the I-579 ramp rather than down on the MLK busway. Compare the following screenshot to the route shown on the [official pdf](https://rideprt.org/pdfs/29.pdf).

![Screenshot_20230323-092235](https://user-images.githubusercontent.com/871691/227289461-233a35e3-c09a-4489-ac1c-74293382ee60.jpg)

**Comment by epicstar** [comment] 2023-04-09 06:11
Thank you @altayhunter for bringing this issue to the forefront. How does the 29 route line compare to the official [truetime website](https://truetime.portauthority.org/map)?
 
![image](https://user-images.githubusercontent.com/7193970/230757522-4c242157-1c0b-4f88-ae5f-c1491f171e4d.png)

Take note, I don't do anything extra to the data PRT gives us through the TrueTime API.

**Comment by altayhunter** [comment] 2023-04-10 02:00
@epicstar The truetime website does have the same mistake that I was pointing out in this issue. It looks like the stop `20287: EAST BUSWAY + PENN STATION A` is being incorrectly snapped to a nearby interstate exit ramp instead of the busway it's on. I reported it to them via their [customer service](https://www.rideprt.org/contact/customer-service/) link on that page.

**Comment by epicstar** [comment] 2023-04-10 04:26
Thank you! Since the issue is on PRT's side and not on app-specific, I'm going to close this for now and label this as "invalid." Thank you for bringing the issue. If you have any more questions, please let me know.

**Closed as completed by epicstar** 2023-04-10 04:26 UTC
Labels: invalid
