### ISSUE TITLE
Buses not showing up

### ISSUE THREAD

**Issue by jainanks** [rectangle-dbmi/Realtime-Port-Authority#158] opened 2015-02-24 01:09 UTC
Routes are visible, but no buses are displayed on these tracks. same problem with a lot of friends using PAT.

**Comment by epicstar** [comment] 2015-02-24 03:30
Yes, very aware. The problem is actually detailed here... https://code.google.com/p/gmaps-api-issues/issues/detail?id=7696. In our code at [line 168](https://github.com/rectangle-dbmi/Realtime-Port-Authority/blob/master/Android/Pittsburgh_Realtime_Tracker/app/src/main/java/rectangledbmi/com/pittsburghrealtimetracker/handlers/RequestTask.java#L168), the method to add the icons no longer works on Google Maps........ We have the icons for the buses as assets but the for the bus stops, they're drawables. What we have to do is make sure that we are using drawables. It may take me 30 minutes to post this.

**Comment by RitwikGupta** [comment] 2015-02-24 05:30
Fixed with latest update #cleverhacks

**Closed by RitwikGupta** 2015-02-24 05:30 UTC
Labels: bug

**Comment by epicstar** [comment] 2015-02-24 06:19
Had to use this to dynamically get our icons... http://stackoverflow.com/questions/9156698/how-to-get-images-dynamically-from-drawable-folder

**Comment by RitwikGupta** [comment] 2015-02-24 06:22
And renaming the files

**Comment by epicstar** [comment] 2015-02-24 06:35
Hopefully we have a while until the workaround breaks.... This is incentive to get real dynamic icons though.
